const express = require('express');
const session = require('express-session');
const bcrypt = require('bcrypt');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const { Pool } = require('pg');
require('dotenv').config();

const app = express();
const PORT = Number(process.env.PORT || 3000);
app.set('trust proxy', 1);
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false
});

app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.use(session({
  secret: process.env.SESSION_SECRET || 'change-me',
  resave: false,
  saveUninitialized: false,
  cookie: { httpOnly: true, sameSite: 'lax', secure: process.env.NODE_ENV === 'production', maxAge: 1000 * 60 * 60 * 8 }
}));

const uploadsDir = path.join(__dirname, 'uploads');
if (!fs.existsSync(uploadsDir)) fs.mkdirSync(uploadsDir, { recursive: true });
const storage = multer.diskStorage({
  destination: (_req, _file, cb) => cb(null, uploadsDir),
  filename: (_req, file, cb) => {
    const ext = path.extname(file.originalname || '').toLowerCase();
    const allowed = ['.jpg', '.jpeg', '.png', '.webp', '.gif'];
    cb(null, `${Date.now()}-${Math.random().toString(36).slice(2, 10)}${allowed.includes(ext) ? ext : '.bin'}`);
  }
});
const upload = multer({ storage, limits: { fileSize: 5 * 1024 * 1024 } });
app.use('/uploads', express.static(uploadsDir));
app.use('/public', express.static(path.join(__dirname, 'public')));

const esc = (v) => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money = (v) => `$${Number(v || 0).toFixed(2)}`;
const q = async (sql, params=[]) => (await pool.query(sql, params)).rows;
const one = async (sql, params=[]) => (await pool.query(sql, params)).rows[0] || null;

function layout(title, body, user={}) {
  return `<!doctype html><html lang="en"><head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${esc(title)} | CHAMPA SPORTS HOUSE</title>
  <style>
    :root{--bg:#f4f7fb;--dark:#0e1726;--green:#16a34a;--red:#dc2626;--muted:#6b7280;--card:#fff;--line:#e5e7eb}
    *{box-sizing:border-box}body{margin:0;background:var(--bg);color:#111827;font:15px/1.5 Arial,sans-serif}
    a{text-decoration:none;color:inherit}.container{width:min(1180px,92%);margin:auto}.header{background:var(--dark);color:#fff;position:sticky;top:0;z-index:20}.nav{min-height:70px;display:flex;align-items:center;justify-content:space-between;gap:20px}.logo{font-size:22px;font-weight:900;letter-spacing:1px}.logo span{display:block;font-size:10px;letter-spacing:2px}.navlinks{display:flex;flex-wrap:wrap;gap:14px;align-items:center}
    .hero{padding:70px 0}.heroBox{background:linear-gradient(135deg,#0e1726,#18304f);color:#fff;border-radius:24px;padding:48px}.hero h1{font-size:clamp(36px,6vw,64px);margin:0 0 12px}.hero p{color:#dbe4f0;max-width:650px;font-size:18px}.section{padding:40px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:20px}.card{background:var(--card);border-radius:18px;box-shadow:0 8px 28px rgba(15,23,42,.07);overflow:hidden}.cardBody{padding:20px}.productImg{width:100%;height:240px;object-fit:cover;background:#e5e7eb}.btn{display:inline-block;border:0;border-radius:10px;padding:11px 15px;background:#1f2937;color:#fff;cursor:pointer}.btn.green{background:var(--green)}.btn.red{background:var(--red)}.btn.secondary{background:#64748b}.muted{color:var(--muted)}.row{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.between{justify-content:space-between}.input,textarea,select{width:100%;padding:11px 13px;border:1px solid #d1d5db;border-radius:10px;background:#fff;font:inherit}.form{display:grid;gap:16px}.field{display:grid;gap:7px}.two{display:grid;grid-template-columns:1fr 1fr;gap:20px}.tableWrap{overflow:auto}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:12px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}.badge{display:inline-block;padding:4px 8px;border-radius:999px;background:#eef2ff}.footer{margin-top:50px;background:#0e1726;color:#dbe4f0;padding:30px 0}.notice{padding:14px 16px;border-radius:12px;background:#eef6ff}.dangerBox{background:#fff1f2;border:1px solid #fecdd3}.stat{padding:24px}.stat h2{margin:6px 0;font-size:30px}.hidden{display:none}
    @media(max-width:800px){.nav{align-items:flex-start;flex-direction:column;padding:14px 0}.two{grid-template-columns:1fr}.heroBox{padding:28px}}
  </style></head><body>
  <header class="header"><div class="container nav"><a class="logo" href="/">CHAMPA<span>SPORTS HOUSE</span></a><nav class="navlinks">
    <a href="/">Home</a><a href="/products">Products</a><a href="/cart">Cart</a>${user.admin ? '<a href="/admin">Admin</a>' : '<a href="/admin/login">Admin</a>'}
  </nav></div></header>
  ${body}
  <footer class="footer"><div class="container">CHAMPA SPORTS HOUSE · Football · Jerseys · Boots · Equipment</div></footer>
  </body></html>`;
}

function requireAdmin(req,res,next){ if(!req.session.admin) return res.redirect('/admin/login'); next(); }
function adminNav(){ return `<div class="row" style="margin:20px 0 30px"><a class="btn" href="/admin">Dashboard</a><a class="btn" href="/admin/products">Products</a><a class="btn" href="/admin/products/new">+ Add Product</a><a class="btn" href="/admin/orders">Orders</a><a class="btn" href="/admin/categories">Categories</a><form method="post" action="/admin/logout"><button class="btn red">Logout</button></form></div>`; }

async function initDb(){
  await pool.query(`
    CREATE TABLE IF NOT EXISTS admins(id SERIAL PRIMARY KEY, username TEXT UNIQUE NOT NULL, password TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS categories(id SERIAL PRIMARY KEY, name TEXT UNIQUE NOT NULL);
    CREATE TABLE IF NOT EXISTS products(id SERIAL PRIMARY KEY, name TEXT NOT NULL, description TEXT DEFAULT '', price NUMERIC(12,2) NOT NULL DEFAULT 0, stock INTEGER NOT NULL DEFAULT 0, category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL, sizes TEXT DEFAULT '', image TEXT);
    CREATE TABLE IF NOT EXISTS orders(id SERIAL PRIMARY KEY, customer_name TEXT NOT NULL, phone TEXT NOT NULL, address TEXT NOT NULL, notes TEXT DEFAULT '', total NUMERIC(12,2) NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'Pending', payment_method TEXT NOT NULL DEFAULT 'COD', payment_status TEXT NOT NULL DEFAULT 'Pending', payment_reference TEXT, payment_transaction_id TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS order_items(id SERIAL PRIMARY KEY, order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE, product_id INTEGER REFERENCES products(id) ON DELETE SET NULL, product_name TEXT NOT NULL, quantity INTEGER NOT NULL, price NUMERIC(12,2) NOT NULL);
  `);
  const categories = await one('SELECT COUNT(*)::int count FROM categories');
  if (categories.count === 0) {
    for (const name of ['Jerseys','Football Boots','Football','Equipment','Sports Shoes','Seybuundo']) await pool.query('INSERT INTO categories(name) VALUES($1) ON CONFLICT DO NOTHING',[name]);
  }
  const admin = await one('SELECT id FROM admins LIMIT 1');
  if (!admin && process.env.ADMIN_USERNAME && process.env.ADMIN_PASSWORD) {
    await pool.query('INSERT INTO admins(username,password) VALUES($1,$2)', [process.env.ADMIN_USERNAME, await bcrypt.hash(process.env.ADMIN_PASSWORD, 12)]);
    console.log('Admin created from .env');
  }
}

app.get('/', async (req,res)=>{
  try{
    const products = await q('SELECT p.*, c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id ORDER BY p.id DESC LIMIT 8');
    res.send(layout('Home',`<main><section class="hero"><div class="container"><div class="heroBox"><h1>CHAMPA SPORTS HOUSE</h1><p>Professional sports shop for jerseys, football boots, balls and equipment.</p><div class="row"><a class="btn green" href="/products">Shop Now</a><a class="btn secondary" href="/cart">View Cart</a></div></div></div></section><section class="section container"><div class="row between"><div><h2>Featured Products</h2><p class="muted">Latest products in the store.</p></div></div><div class="grid">${products.map(productCard).join('')||'<p class="muted">No products yet.</p>'}</div></section></main>`, {admin:!!req.session.admin}));
  }catch(e){console.error(e);res.status(500).send('Server error');}
});

function productCard(p){ return `<article class="card">${p.image?`<img class="productImg" src="${esc(p.image)}" alt="${esc(p.name)}">`:''}<div class="cardBody"><div class="muted">${esc(p.category_name||'Sports')}</div><h3>${esc(p.name)}</h3><p><strong>${money(p.price)}</strong></p><p class="muted">Stock: ${p.stock}</p><form method="post" action="/cart/add" class="row"><input type="hidden" name="product_id" value="${p.id}"><input class="input" style="width:90px" type="number" name="quantity" value="1" min="1" max="${Math.max(1,p.stock)}"><button class="btn green" type="submit" ${p.stock<1?'disabled':''}>Add to Cart</button></form></div></article>`; }

app.get('/products', async(req,res)=>{ try{ const search=String(req.query.search||'').trim(); const params=[]; let where=''; if(search){params.push(`%${search}%`);where='WHERE p.name ILIKE $1 OR p.description ILIKE $1';} const products=await q(`SELECT p.*, c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id ${where} ORDER BY p.id DESC`,params); res.send(layout('Products',`<section class="section container"><div class="row between"><div><h1>Products</h1><p class="muted">Search and shop sports products.</p></div><form method="get" action="/products" class="row"><input class="input" style="width:260px" name="search" value="${esc(search)}" placeholder="Search"><button class="btn">Search</button></form></div><div class="grid" style="margin-top:24px">${products.map(productCard).join('')||'<p class="muted">No products found.</p>'}</div></section>`,{admin:!!req.session.admin})); }catch(e){console.error(e);res.status(500).send('Server error');} });

app.post('/cart/add', async(req,res)=>{ try{ const id=Number(req.body.product_id), qty=Math.max(1,Number(req.body.quantity||1)); const p=await one('SELECT id,stock FROM products WHERE id=$1',[id]); if(!p)return res.status(404).send('Product not found'); if(qty>p.stock)return res.status(400).send('Not enough stock'); const cart=Array.isArray(req.session.cart)?req.session.cart:[]; const item=cart.find(x=>Number(x.product_id)===id); if(item)item.quantity+=qty; else cart.push({product_id:id,quantity:qty}); req.session.cart=cart; res.redirect('/cart'); }catch(e){console.error(e);res.status(500).send('Server error');} });
app.post('/cart/update', async(req,res)=>{ try{const id=Number(req.body.product_id),qty=Math.max(1,Number(req.body.quantity||1)); const p=await one('SELECT stock FROM products WHERE id=$1',[id]); const cart=req.session.cart||[]; const item=cart.find(x=>Number(x.product_id)===id); if(item&&p)item.quantity=Math.min(qty,Number(p.stock)); res.redirect('/cart');}catch(e){console.error(e);res.status(500).send('Server error');}});
app.post('/cart/remove',(req,res)=>{ const id=Number(req.body.product_id); req.session.cart=(req.session.cart||[]).filter(x=>Number(x.product_id)!==id); res.redirect('/cart'); });

app.get('/cart', async(req,res)=>{ try{const cart=req.session.cart||[]; const ids=cart.map(x=>Number(x.product_id)); let products=[]; if(ids.length)products=await q('SELECT * FROM products WHERE id=ANY($1::int[])',[ids]); let total=0; const items=cart.map(x=>{const p=products.find(y=>Number(y.id)===Number(x.product_id)); if(!p)return null; const qty=Math.min(Math.max(1,Number(x.quantity||1)),Number(p.stock)); const sub=Number(p.price)*qty; total+=sub; return {p,qty,sub};}).filter(Boolean); res.send(layout('Cart',`<section class="section container"><h1>Your Cart</h1><div class="card"><div class="cardBody">${items.length?items.map(i=>`<div class="row between" style="padding:14px 0;border-bottom:1px solid #eee"><div><strong>${esc(i.p.name)}</strong><div class="muted">${money(i.p.price)} each</div></div><form method="post" action="/cart/update" class="row"><input type="hidden" name="product_id" value="${i.p.id}"><input class="input" style="width:80px" type="number" min="1" max="${i.p.stock}" name="quantity" value="${i.qty}"><button class="btn">Update</button></form><strong>${money(i.sub)}</strong><form method="post" action="/cart/remove"><input type="hidden" name="product_id" value="${i.p.id}"><button class="btn red">Remove</button></form></div>`).join(''):`<p class="muted">Your cart is empty.</p>`}<div class="row between" style="margin-top:20px"><strong>Total</strong><strong style="font-size:24px">${money(total)}</strong></div>${items.length?`<div style="margin-top:20px"><a class="btn green" href="/checkout">Checkout</a></div>`:''}</div></div></section>`,{admin:!!req.session.admin}));}catch(e){console.error(e);res.status(500).send('Server error');}});

app.get('/checkout',async(req,res)=>{ const cart=req.session.cart||[]; if(!cart.length)return res.redirect('/cart'); const ids=cart.map(x=>Number(x.product_id)); try{const products=await q('SELECT * FROM products WHERE id=ANY($1::int[])',[ids]); let total=0; const items=cart.map(x=>{const p=products.find(y=>Number(y.id)===Number(x.product_id));if(!p)return null;const qty=Number(x.quantity||1);const sub=Number(p.price)*qty;total+=sub;return {p,qty,sub};}).filter(Boolean); res.send(layout('Checkout',`<section class="section container"><div class="two"><div class="card"><div class="cardBody"><h1>Checkout</h1><form method="post" action="/checkout" class="form"><div class="field"><label>Full Name</label><input class="input" name="customer_name" required></div><div class="field"><label>Phone</label><input class="input" name="phone" placeholder="+252..." required></div><div class="field"><label>Address</label><textarea name="address" required></textarea></div><div class="field"><label>Notes</label><textarea name="notes"></textarea></div><div class="field"><label>Payment Method</label><select class="input" name="payment_method"><option value="COD">Cash on Delivery</option><option value="WAAFI">WaafiPay</option></select></div><button class="btn green">Place Order</button></form></div></div><aside class="card"><div class="cardBody"><h2>Order Summary</h2>${items.map(i=>`<div class="row between"><span>${esc(i.p.name)} × ${i.qty}</span><strong>${money(i.sub)}</strong></div>`).join('')}<hr><div class="row between"><strong>Total</strong><strong>${money(total)}</strong></div></div></aside></div></section>`,{admin:!!req.session.admin}));}catch(e){console.error(e);res.status(500).send('Server error');} });

app.post('/checkout',async(req,res)=>{ const client=await pool.connect(); try{const cart=req.session.cart||[]; if(!cart.length)return res.redirect('/cart'); const name=String(req.body.customer_name||'').trim(),phone=String(req.body.phone||'').trim(),address=String(req.body.address||'').trim(),notes=String(req.body.notes||'').trim(),method=String(req.body.payment_method||'COD').trim(); if(!name||!phone||!address)return res.status(400).send('Please fill all required fields.'); if(!['COD','WAAFI'].includes(method))return res.status(400).send('Invalid payment method.'); await client.query('BEGIN'); let total=0; const items=[]; for(const c of cart){const p=(await client.query('SELECT * FROM products WHERE id=$1 FOR UPDATE',[Number(c.product_id)])).rows[0]; if(!p)throw new Error('Product not found'); const qty=Math.max(1,Number(c.quantity||1)); if(qty>Number(p.stock))throw new Error(`${p.name} does not have enough stock`); total+=Number(p.price)*qty; items.push({p,qty});} const order=(await client.query(`INSERT INTO orders(customer_name,phone,address,notes,total,status,payment_method,payment_status) VALUES($1,$2,$3,$4,$5,'Pending',$6,'Pending') RETURNING id`,[name,phone,address,notes,total,method])).rows[0]; for(const i of items){await client.query('INSERT INTO order_items(order_id,product_id,product_name,quantity,price) VALUES($1,$2,$3,$4,$5)',[order.id,i.p.id,i.p.name,i.qty,i.p.price]); await client.query('UPDATE products SET stock=stock-$1 WHERE id=$2',[i.qty,i.p.id]);} await client.query('COMMIT'); req.session.cart=[]; if(method==='WAAFI'&&process.env.WAAFI_ENABLED==='true') return res.redirect(`/payment/waafi/${order.id}`); res.redirect(`/order/${order.id}`); }catch(e){await client.query('ROLLBACK');console.error(e);res.status(500).send(esc(e.message||'Could not create order'));}finally{client.release();} });

app.get('/order/:id',async(req,res)=>{try{const order=await one('SELECT * FROM orders WHERE id=$1',[req.params.id]);if(!order)return res.status(404).send('Order not found');const items=await q('SELECT * FROM order_items WHERE order_id=$1 ORDER BY id',[req.params.id]);const msg=['CHAMPA SPORTS HOUSE','',`Order #${order.id}`,'',`Customer: ${order.customer_name}`,`Phone: ${order.phone}`,`Address: ${order.address}`,'','Products:',...items.map(i=>`- ${i.product_name} x${i.quantity} = ${money(Number(i.price)*Number(i.quantity))}`),'',`TOTAL: ${money(order.total)}`,`Payment: ${order.payment_method}`,`Payment Status: ${order.payment_status}`].join('\n');const wa=String(process.env.WHATSAPP_NUMBER||'').replace(/\D/g,'');const waUrl=wa?`https://wa.me/${wa}?text=${encodeURIComponent(msg)}`:'#';res.send(layout(`Order #${order.id}`,`<section class="section container"><div class="card"><div class="cardBody"><h1>Order Received ✅</h1><p>Thank you, <strong>${esc(order.customer_name)}</strong>.</p><p>Order #<strong>${order.id}</strong></p>${items.map(i=>`<div class="row between"><span>${esc(i.product_name)} × ${i.quantity}</span><strong>${money(Number(i.price)*Number(i.quantity))}</strong></div>`).join('')}<hr><div class="row between"><strong>Total</strong><strong>${money(order.total)}</strong></div><p>Payment: <strong>${esc(order.payment_method)}</strong> · <strong>${esc(order.payment_status)}</strong></p><a class="btn green" href="${waUrl}" target="_blank">Send Order on WhatsApp</a></div></div></section>`,{admin:!!req.session.admin}));}catch(e){console.error(e);res.status(500).send('Server error');}});

app.get('/admin/login',(req,res)=>{if(req.session.admin)return res.redirect('/admin');res.send(layout('Admin Login',`<section class="section container" style="max-width:480px"><div class="card"><div class="cardBody"><h1>Admin Login</h1><form method="post" action="/admin/login" class="form"><div class="field"><label>Username</label><input class="input" name="username" required></div><div class="field"><label>Password</label><input class="input" type="password" name="password" required></div><button class="btn green">Login</button></form></div></div></section>`,{}));});
app.post('/admin/login',async(req,res)=>{try{const u=String(req.body.username||'').trim(),p=String(req.body.password||'');const admin=await one('SELECT * FROM admins WHERE username=$1',[u]);if(!admin||!(await bcrypt.compare(p,admin.password)))return res.status(401).send('Invalid username or password');req.session.regenerate(err=>{if(err)return res.status(500).send('Session error');req.session.admin={id:admin.id,username:admin.username};req.session.save(()=>res.redirect('/admin'));});}catch(e){console.error(e);res.status(500).send('Login error');}});
app.post('/admin/logout',requireAdmin,(req,res)=>req.session.destroy(()=>res.redirect('/')));

app.get('/admin',requireAdmin,async(req,res)=>{try{const pc=await one('SELECT COUNT(*)::int count FROM products'),oc=await one('SELECT COUNT(*)::int count FROM orders'),pending=await one("SELECT COUNT(*)::int count FROM orders WHERE status='Pending'"),rev=await one("SELECT COALESCE(SUM(total),0) total FROM orders WHERE status<>'Cancelled'");res.send(layout('Admin',`<section class="section container"><h1>Admin Dashboard</h1>${adminNav()}<div class="grid"><div class="card"><div class="stat"><div class="muted">Products</div><h2>${pc.count}</h2></div></div><div class="card"><div class="stat"><div class="muted">Orders</div><h2>${oc.count}</h2></div></div><div class="card"><div class="stat"><div class="muted">Pending</div><h2>${pending.count}</h2></div></div><div class="card"><div class="stat"><div class="muted">Revenue</div><h2>${money(rev.total)}</h2></div></div></div></section>`,{admin:true}));}catch(e){console.error(e);res.status(500).send('Server error');}});

app.get('/admin/products',requireAdmin,async(req,res)=>{try{const products=await q('SELECT p.*,c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id ORDER BY p.id DESC');res.send(layout('Admin Products',`<section class="section container"><h1>Products</h1>${adminNav()}<div class="card"><div class="tableWrap"><table class="table"><thead><tr><th>ID</th><th>Name</th><th>Price</th><th>Stock</th><th>Category</th><th>Action</th></tr></thead><tbody>${products.map(p=>`<tr><td>${p.id}</td><td>${esc(p.name)}</td><td>${money(p.price)}</td><td>${p.stock}</td><td>${esc(p.category_name||'-')}</td><td><a class="btn secondary" href="/admin/products/${p.id}/edit">Edit</a></td></tr>`).join('')}</tbody></table></div></div></section>`,{admin:true}));}catch(e){console.error(e);res.status(500).send('Server error');}});
app.get('/admin/products/new',requireAdmin,async(req,res)=>{const cats=await q('SELECT * FROM categories ORDER BY name');res.send(layout('Add Product',`<section class="section container" style="max-width:850px"><h1>Add Product</h1>${adminNav()}<div class="card"><div class="cardBody"><form method="post" action="/admin/products" enctype="multipart/form-data" class="form"><div class="field"><label>Name</label><input class="input" name="name" required></div><div class="field"><label>Description</label><textarea name="description"></textarea></div><div class="two"><div class="field"><label>Price</label><input class="input" name="price" type="number" step="0.01" min="0" required></div><div class="field"><label>Stock</label><input class="input" name="stock" type="number" min="0" required></div></div><div class="field"><label>Category</label><select class="input" name="category_id" required><option value="">Select</option>${cats.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Sizes</label><input class="input" name="sizes" placeholder="S,M,L,XL,XXL"></div><div class="field"><label>Image</label><input class="input" type="file" name="image" accept="image/*"></div><button class="btn green">Add Product</button></form></div></div></section>`,{admin:true}));});
app.post('/admin/products',requireAdmin,upload.single('image'),async(req,res)=>{try{const name=String(req.body.name||'').trim(),desc=String(req.body.description||'').trim(),price=Number(req.body.price),stock=Number(req.body.stock),cat=Number(req.body.category_id),sizes=String(req.body.sizes||'').trim();if(!name||!Number.isFinite(price)||price<0||!Number.isInteger(stock)||stock<0||!Number.isInteger(cat))return res.status(400).send('Invalid product data');const image=req.file?`/uploads/${req.file.filename}`:null;await pool.query('INSERT INTO products(name,description,price,stock,category_id,sizes,image) VALUES($1,$2,$3,$4,$5,$6,$7)',[name,desc,price,stock,cat,sizes,image]);res.redirect('/admin/products');}catch(e){console.error(e);res.status(500).send('Could not save product');}});
app.get('/admin/products/:id/edit',requireAdmin,async(req,res)=>{const p=await one('SELECT * FROM products WHERE id=$1',[req.params.id]);if(!p)return res.status(404).send('Not found');const cats=await q('SELECT * FROM categories ORDER BY name');res.send(layout('Edit Product',`<section class="section container" style="max-width:850px"><h1>Edit Product</h1>${adminNav()}<div class="card"><div class="cardBody"><form method="post" action="/admin/products/${p.id}" enctype="multipart/form-data" class="form"><div class="field"><label>Name</label><input class="input" name="name" value="${esc(p.name)}" required></div><div class="field"><label>Description</label><textarea name="description">${esc(p.description||'')}</textarea></div><div class="two"><div class="field"><label>Price</label><input class="input" name="price" type="number" step="0.01" value="${p.price}" required></div><div class="field"><label>Stock</label><input class="input" name="stock" type="number" value="${p.stock}" required></div></div><div class="field"><label>Category</label><select class="input" name="category_id">${cats.map(c=>`<option value="${c.id}" ${Number(c.id)===Number(p.category_id)?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Sizes</label><input class="input" name="sizes" value="${esc(p.sizes||'')}"></div>${p.image?`<img class="productImg" style="max-width:240px;height:200px" src="${esc(p.image)}">`:''}<div class="field"><label>Replace Image</label><input class="input" type="file" name="image" accept="image/*"></div><button class="btn green">Save Changes</button></form><hr style="margin:30px 0"><form method="post" action="/admin/products/${p.id}/delete" onsubmit="return confirm('Delete this product?')"><button class="btn red">Delete Product</button></form></div></div></section>`,{admin:true}));});
app.post('/admin/products/:id',requireAdmin,upload.single('image'),async(req,res)=>{try{const p=await one('SELECT * FROM products WHERE id=$1',[req.params.id]);if(!p)return res.status(404).send('Not found');const name=String(req.body.name||'').trim(),desc=String(req.body.description||'').trim(),price=Number(req.body.price),stock=Number(req.body.stock),cat=Number(req.body.category_id),sizes=String(req.body.sizes||'').trim();const image=req.file?`/uploads/${req.file.filename}`:p.image;await pool.query('UPDATE products SET name=$1,description=$2,price=$3,stock=$4,category_id=$5,sizes=$6,image=$7 WHERE id=$8',[name,desc,price,stock,cat,sizes,image,req.params.id]);res.redirect('/admin/products');}catch(e){console.error(e);res.status(500).send('Could not update');}});
app.post('/admin/products/:id/delete',requireAdmin,async(req,res)=>{try{await pool.query('DELETE FROM products WHERE id=$1',[req.params.id]);res.redirect('/admin/products');}catch(e){console.error(e);res.status(500).send('Could not delete');}});

app.get('/admin/orders',requireAdmin,async(req,res)=>{const orders=await q('SELECT * FROM orders ORDER BY id DESC');res.send(layout('Orders',`<section class="section container"><h1>Orders</h1>${adminNav()}<div class="card"><div class="tableWrap"><table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th><th>Action</th></tr></thead><tbody>${orders.map(o=>`<tr><td>#${o.id}</td><td>${esc(o.customer_name)}<br>${esc(o.phone)}</td><td>${money(o.total)}</td><td>${esc(o.payment_method)} / ${esc(o.payment_status)}</td><td>${esc(o.status)}</td><td><a class="btn secondary" href="/admin/orders/${o.id}">View</a></td></tr>`).join('')}</tbody></table></div></div></section>`,{admin:true}));});
app.get('/admin/orders/:id',requireAdmin,async(req,res)=>{const o=await one('SELECT * FROM orders WHERE id=$1',[req.params.id]);if(!o)return res.status(404).send('Not found');const items=await q('SELECT * FROM order_items WHERE order_id=$1 ORDER BY id',[req.params.id]);res.send(layout(`Order #${o.id}`,`<section class="section container"><h1>Order #${o.id}</h1>${adminNav()}<div class="two"><div class="card"><div class="cardBody"><h2>Customer</h2><p><b>Name:</b> ${esc(o.customer_name)}</p><p><b>Phone:</b> ${esc(o.phone)}</p><p><b>Address:</b> ${esc(o.address)}</p><p><b>Notes:</b> ${esc(o.notes||'-')}</p></div></div><div class="card"><div class="cardBody"><h2>Payment</h2><p>${esc(o.payment_method)} / ${esc(o.payment_status)}</p><form method="post" action="/admin/orders/${o.id}/payment-status" class="form"><select class="input" name="payment_status">${['Pending','Paid','Failed','Cancelled'].map(s=>`<option ${o.payment_status===s?'selected':''}>${s}</option>`).join('')}</select><button class="btn green">Update Payment</button></form></div></div></div><div class="card" style="margin-top:20px"><div class="cardBody"><h2>Items</h2>${items.map(i=>`<div class="row between" style="padding:10px 0;border-bottom:1px solid #eee"><span>${esc(i.product_name)} × ${i.quantity}</span><strong>${money(Number(i.price)*Number(i.quantity))}</strong></div>`).join('')}<div class="row between" style="margin-top:18px"><strong>Total</strong><strong>${money(o.total)}</strong></div></div></div><div class="card" style="margin-top:20px"><div class="cardBody"><h2>Order Status</h2><form method="post" action="/admin/orders/${o.id}/status" class="form"><select class="input" name="status">${['Pending','Confirmed','Processing','Delivered','Cancelled'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select><button class="btn green">Update Status</button></form></div></div></section>`,{admin:true}));});
app.post('/admin/orders/:id/status',requireAdmin,async(req,res)=>{const allowed=['Pending','Confirmed','Processing','Delivered','Cancelled'];if(!allowed.includes(req.body.status))return res.status(400).send('Invalid status');await pool.query('UPDATE orders SET status=$1 WHERE id=$2',[req.body.status,req.params.id]);res.redirect(`/admin/orders/${req.params.id}`);});
app.post('/admin/orders/:id/payment-status',requireAdmin,async(req,res)=>{const allowed=['Pending','Paid','Failed','Cancelled'];if(!allowed.includes(req.body.payment_status))return res.status(400).send('Invalid payment status');await pool.query('UPDATE orders SET payment_status=$1 WHERE id=$2',[req.body.payment_status,req.params.id]);res.redirect(`/admin/orders/${req.params.id}`);});

app.get('/admin/categories',requireAdmin,async(req,res)=>{const cats=await q('SELECT c.id,c.name,COUNT(p.id)::int product_count FROM categories c LEFT JOIN products p ON p.category_id=c.id GROUP BY c.id,c.name ORDER BY c.name');res.send(layout('Categories',`<section class="section container"><h1>Categories</h1>${adminNav()}<div class="card"><div class="cardBody"><form method="post" action="/admin/categories" class="form"><div class="field"><label>Category Name</label><input class="input" name="name" required></div><button class="btn green">Add Category</button></form></div></div><div class="card" style="margin-top:20px"><div class="tableWrap"><table class="table"><thead><tr><th>ID</th><th>Name</th><th>Products</th></tr></thead><tbody>${cats.map(c=>`<tr><td>${c.id}</td><td>${esc(c.name)}</td><td>${c.product_count}</td></tr>`).join('')}</tbody></table></div></div></section>`,{admin:true}));});
app.post('/admin/categories',requireAdmin,async(req,res)=>{const name=String(req.body.name||'').trim();if(!name)return res.status(400).send('Name required');await pool.query('INSERT INTO categories(name) VALUES($1) ON CONFLICT(name) DO NOTHING',[name]);res.redirect('/admin/categories');});

// WaafiPay: payment page shell. Real gateway verification should be added with your merchant credentials.
app.get('/payment/waafi/:id',async(req,res)=>{if(process.env.WAAFI_ENABLED!=='true')return res.status(503).send('WaafiPay is not enabled yet.');const o=await one('SELECT * FROM orders WHERE id=$1',[req.params.id]);if(!o)return res.status(404).send('Order not found');res.send(layout('WaafiPay',`<section class="section container" style="max-width:650px"><div class="card"><div class="cardBody"><h1>WaafiPay</h1><p>Order #${o.id}</p><p>Amount: <strong>${money(o.total)}</strong></p><p class="notice">Gateway credentials are configured separately. This project does not mark payments as Paid without gateway confirmation.</p></div></div></section>`,{admin:!!req.session.admin}));});

app.get('/health',(_req,res)=>res.json({ok:true,service:'champa-sports-house'}));

async function start(){
  if(!process.env.DATABASE_URL){console.error('DATABASE_URL is missing. Copy .env.example to .env and configure PostgreSQL.');process.exit(1);}
  try{await initDb(); app.listen(PORT,()=>console.log(`CHAMPA SPORTS HOUSE running at http://localhost:${PORT}`));}
  catch(err){console.error('Startup error:',err);process.exit(1);}
}
start();
